### ISSUE TITLE
Python version conflict: numba requires Python >=3.7, readme specifies Python >=3.6

### ISSUE THREAD

**Issue by thekugelmeister** [lareaulab/psix#2]
When installing psix using the command provided in the readme, in an environment created using Python 3.6.9, I experience the following errors when installing `numba`:

```
Collecting numba>=0.43.1 (from psix==0.9.1)
  Using cached https://files.pythonhosted.org/packages/e3/7d/3d61160836e49f40913741c464f119551c15ed371c1d91ea50308495b93b/numba-0.53.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-hvyaokwh/numpy-1.21.2/setup.py", line 34, in <module>
        def _guard_py_ver():
    RuntimeError: Python version >= 3.7 required.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f1xlfno6/numba/setup.py", line 424, in <module>
        setup(**metadata)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/mnt/lareaulab/jmarcus/jeremy-env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-hvyaokwh/numpy-1.21.2/setup.py", line 34, in <module>
        def _guard_py_ver():
    RuntimeError: Python version >= 3.7 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f1xlfno6/numba/
```

**Comment by cfbuenabadn** [comment]
This is an error with the readme. It should be Python >= 3.7. Thanks for catching that up. Please let me know if you have issues installing with Python 3.7 or higher.

**Comment by thekugelmeister** [comment]
Works! Thank you for addressing it.
